// legacy/vite/src/pages/Login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-100">
    <div class="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
      <h1 class="text-3xl font-bold text-center mb-8 text-blue-600">InfraMind</h1>
      
      <form @submit.prevent="handleLogin" class="space-y-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Email</label>
          <input 
            v-model="email" 
            type="email" 
            required
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="manager@example.com"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Password</label>
          <input 
            v-model="password" 
            type="password" 
            required
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="Manager123!@#"
          />
        </div>

        <button 
          type="submit"
          :disabled="loading"
          class="w-full bg-blue-600 text-white py-2 rounded-lg font-medium hover:bg-blue-700 disabled:bg-gray-400 transition"
        >
          {{ loading ? 'Logging in...' : 'Sign In' }}
        </button>

        <div v-if="error" class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
          {{ error }}
        </div>
      </form>

      <div class="mt-6 p-4 bg-gray-50 rounded text-sm text-gray-600">
        <p class="font-semibold mb-2">Test Credentials:</p>
        <p>📧 manager@example.com</p>
        <p>🔑 Manager123!@#</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const email = ref('manager@example.com')
const password = ref('Manager123!@#')
const loading = ref(false)
const error = ref('')
const router = useRouter()
const authStore = useAuthStore()

const handleLogin = async () => {
  loading.value = true
  error.value = ''

  const success = await authStore.login(email.value, password.value)
  
  if (success) {
    router.push('/')
  } else {
    error.value = 'Invalid email or password'
  }
  
  loading.value = false
}
</script>

// src/app/(auth)/login/page.tsx
"use client";

import React from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import GlassCard from '@/src/components/ui/GlassCard';
import { createSessionAction } from '@/src/app/actions';

export default function LoginPage() {
  const router = useRouter();
  const [pending, startTransition] = React.useTransition();
  const [error, setError] = React.useState('');

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError('');
    const formData = new FormData(event.currentTarget);
    const email = String(formData.get('email') ?? '');
    const password = String(formData.get('password') ?? '');

    startTransition(async () => {
      try {
        // Call PHP backend login
        const user = await createSessionAction({ email, password });
        
        if (!user) {
          setError('Login failed. Please check your credentials.');
          return;
        }
        
        // Redirect based on role
        const target = user.role === 'MANAGER' ? '/manager' : user.role === 'OWNER' ? '/owner' : '/employee';
        router.push(target);
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        setError(message || 'Login failed. Please try again.');
      }
    });
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100">
      <main className="mx-auto flex max-w-md flex-col gap-6 px-6 py-16">
        <header className="space-y-2 text-center">
          <h1 className="text-2xl font-semibold text-white">Sign in to InfraMind</h1>
          <p className="text-sm text-slate-400">Access your role-based workspace.</p>
        </header>

        <GlassCard>
          <form onSubmit={handleSubmit} className="space-y-4">
            <input
              name="email"
              type="email"
              placeholder="Email"
              required
              className="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-white placeholder:text-slate-500 focus:border-blue-400 focus:outline-none"
            />
            <input
              name="password"
              type="password"
              placeholder="Password"
              required
              className="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-white placeholder:text-slate-500 focus:border-blue-400 focus:outline-none"
            />
            {error && <p className="text-xs text-rose-400">{error}</p>}
            <button
              type="submit"
              disabled={pending}
              className="w-full rounded-xl bg-blue-500 px-4 py-2 text-xs font-semibold text-white hover:bg-blue-400 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {pending ? 'Signing in…' : 'Sign in'}
            </button>
          </form>
        </GlassCard>

        <p className="text-center text-xs text-slate-400">
          New here?{' '}
          <Link href="/signup" className="text-blue-300 hover:text-blue-200">
            Create an account
          </Link>
        </p>
      </main>
    </div>
  );
}
